# Generated by Django 4.1.4 on 2023-07-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_order_completed_order_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reviewed_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
