# Generated by Django 4.1.4 on 2023-07-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_rename_title_feedback_name_remove_feedback_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcharge',
            old_name='perKM',
            new_name='extra',
        ),
    ]
