# Generated by Django 4.1.4 on 2023-09-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rename_perkm_carcharge_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageevent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='packagegallery',
            name='description',
        ),
    ]
