# Generated by Django 4.1.4 on 2023-09-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_remove_packageevent_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='days',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='nights',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
