# Generated by Django 4.1.4 on 2023-09-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_package_days_alter_package_nights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='departure',
        ),
        migrations.AddField(
            model_name='package',
            name='end',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='start',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
